services:
  client:
    image: client
    build:
      context: client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    restart: 'always'
    volumes:
      - ./client:/app
      - /app/node_modules
